select * from customer limit 20

--Q1. What is the total revenue generated by male vs. female customes?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

--Q3. Which are the top 5 products with the highest average review rating? 
     --to round off the AVG to 2 place "ROUND".
	 --ROUND fnc DOESN'T WORK ON DOUBLE PRECISION so we will typecast it as 'numeric'
select item_purchased, ROUND(AVG(review_rating::numeric),2) as "Average Product Raing"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping?
select shipping_type,
ROUND(AVG(purchase_amount),2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend time and total revenue b/w subscriber & non-sbscribers?
select subscription_status,
COUNT(customer_id) as total_customers,
ROUND(AVG(purchase_amount),2) as avg_spend,
ROUND(SUM(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by total_revenue, avg_spend desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
   -- Discount rate per product
   -- grouping the items & finding the percentage (*100) of times  discount was applied to an item out of the total no. of time item was sold
select item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Q7. Segment customers into New, Returning, and Loyal.
   -- based on their total number of previous purchase, nd show the count of each segment.
with customer_type as (
select customer_id, previous_purchases,
case
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer
)

select customer_segment, count(*) as "Number of Customers"
from customer_type
group by customer_segment

--Q8. What are the top 3 most purchased products within each category?
	-- Advanced Query (need window function to rank products by total product in each category & then pick top 3)
	-- Need CTE (item_counts) for this query
with item_counts as (
select category,
item_purchased,
count(customer_id) as total_orders,
	--WINDOW FUNCTION to rank the products
	-- 1. RANK 2. DENSE_RANK 3. ROW_NUMBER(applied in this case)
row_number() over (partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to be subscribers?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status

--Q10. What is the revenue contribution of each age group?
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc;